sudo: required
services::
  - docker

before_install:
  - docker build -t anandkoligudda/docker-react -f Dockerfile.dev .

scripts:
  - docker run anandkoligudda/docker-react npm run test -- --coverage